appname: camsi-boot
server:
  name: camsi-boot
  email: hujs@colla.cc
  runmode: dev
  password: "123456"
http:
  httpport: 8080
  httpaddr: 127.0.0.1
  autorender: true
  recoverpanic: true
  viewspath: view
  enablegzip: true
database:
  drivername: postgres
  host: localhost
  port: 5433
  dbname: postgres
  user: postgres
  password: 123456
  readonly: false
  sslmode: disable
  timeZone: Asia/Shanghai
  maxIdleConns: 10
  maxOpenConns: 30
  connMaxLifetime: 30000
  showSQL: true
libp2p:
  port: 3719